### ISSUE TITLE
ToastIt-JS lost visibility while <dialog> is open

### ISSUE THREAD

**Issue by FernandoIstea** [mobilepadawan/toastit-js#8]
ToastIt JS is inserted over the HTML **body** element. This works fine while a HTML **<dialog>** is not showing in the HTML document.

When you open a <dialog> element and code a logic to interact with **ToastIt JS**, the ToastIt div is located behind the `::backdrop` CSS style applied over the **<dialog>** element.

**Comment by mobilepadawan** [comment]
Thanks for reporting this issue.

You can fix alternatively this issue by editing the `ToastItv.1.0.js` located at `/developer` folder.

Identify the follow line:
```
document.querySelector('body').insertAdjacentElement('beforebegin', divToast)
```

and modify with this another lines:

```
if (document.querySelector("dialog[open]") {
    document.querySelector('dialog').insertAdjacentElement('beforebegin', divToast)
} else {
    document.querySelector('body').insertAdjacentElement('beforebegin', divToast)
}
```

I'll apply this change in the code in the following weeks.
